### ISSUE TITLE
Transformer based Multilingual document Embedding model

### ISSUE THREAD

**Issue by ever4244** [raymondhs/fairseq-laser#6]
Hi Raymondhs:
   Long time no see!    
   I wrote a paper and use your code framework for the laser baseline and utility.

   It is called `Transformer based Multilingual document Embedding model' for the upcoming EACL conference (deadline Sep. 20th), in the attachment is my manuscript:
  https://arxiv.org/pdf/2008.08567.pdf

  It there any related publication by you that I need to cite in the paper?

  May I ask for your comment and advice about my paper? Since there is still about one month to go, do you have any suggestions on improving the acceptance chance (e.g., are there some important experiments that need to be done)? I especially welcome negative comments that point out the drawback and flaws, so I can have a timely fix.

  Of course,  If you provide your original unique ideas that change the content of the paper in a significant way I can include you in the author list.  (Need to be agreed by my co-author )

  BTW:
     You can send an email to davidlee9918@gmail.com for negative comments :)   or I can send for you if I may have your email address.

                                                                                               Regards!
                                                                                                                 Wei

**Comment by raymondhs** [comment]
Hello, glad to know you are using the code for your research. :) I don't have any related publication yet, but if you need to cite you may use this BibTeX entry:
```
@misc{fairseqlaser20,
    title  = {fairseq-laser: Implementing LASER architecture using fairseq library},
    author = {Susanto, Raymond Hendy},
    url    = {https://github.com/raymondhs/fairseq-laser},
    year   = {2020}
}
```
For your paper, I guess you can try more various tasks if you want to, such as similarity search, bitext mining (like those in LASER), or other NLP tasks. Btw, there is a recent paper from AAAI'20 along this topic: https://arxiv.org/pdf/1909.00437.pdf. 
All the best!

**Comment by ever4244** [comment]
> Hello, glad to know you are using the code for your research. :) I don't have any related publication yet, but if you need to cite you may use this BibTeX entry:
> 
> ```
> @misc{fairseqlaser20,
>     title  = {fairseq-laser: Implementing LASER architecture using fairseq library},
>     author = {Susanto, Raymond Hendy},
>     url    = {https://github.com/raymondhs/fairseq-laser},
>     year   = {2020}
> }
> ```
> 
> For your paper, I guess you can try more various tasks if you want to, such as similarity search, bitext mining (like those in LASER), or other NLP tasks. Btw, there is a recent paper from AAAI'20 along this topic: https://arxiv.org/pdf/1909.00437.pdf.
> All the best!

Thanks!
