### ISSUE TITLE
Can you pelase add a license?

### ISSUE THREAD

**Issue by jayargo** [raymondhs/fairseq-laser#7]
Hi,

Thanks for putting this together! Any chance you could add a license? There's an overview of how to do that here:

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

Thanks!

**Comment by raymondhs** [comment]
Hello, I just added MIT license for this repo. Thanks for your interest!

**Comment by jayargo** [comment]
Thanks so much, really appreciate that!
